# Site settings
# in the templates available like {{ site.myvariable }}.
url: https://thedreamcatcher4.me
enforce_ssl: thedreamcatcher4.me
title: thedreamcatcher4 quotes
email: thedreamcatcher4team@gmail.com
brand: 'thedreamcatcher4'
headline: Four dreamers with a zeal for writing
description: > # this means to ignore newlines until "baseurl:"
  thedreamcatcher4 quotes
  Our Insta Profile Website
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://example.com" # the base hostname & protocol for your site
copyright: 2017 TheDreamcatcher4, Inc. All Rights Reserved.

meta_author: thedreamcatcher4

# Build settings
markdown: kramdown

# Account ids
snapwidget: 377775

# Contacts
#phone: +1-800-555-2016

# Tracking
googleAnalitycsID: UA-99078691-1

