# Site settings
# in the templates available like {{ site.myvariable }}.
title: TheDreamcathcer4
email: thedreamcatcherteam4@gmail.com
brand: '@the_dreamcatcher.4'
headline: Four dreamers with a zeal for writing
description: > # this means to ignore newlines until "baseurl:"
  New Site
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://example.com" # the base hostname & protocol for your site
copyright: 2017 TheDreamcatcher4, Inc. All Rights Reserved.

# Build settings
markdown: kramdown

# Account ids
snapwidget: 377775

# Contacts
email: thedreamcatcherteam4@gmail.com
#phone: +1-800-555-2016

# Tracking
#googleAnalitycsID: UA-83933844-1

